import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
        <nav style={{backgroundColor: "#ccc",
            display: "flex",
            alignItems : "center",
            justifyContent: "space-evenly"
        }}>
          <Link href={'/pagina2'}>Pagina 2</Link> <br />
          <Link href={'/pagina3'}>Pagina 3</Link>
          <Link href={'pagina3?id=5'}>Pagina 3 com id</Link>
          <Link href={'/'}>Back</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
